### ISSUE TITLE
User profile -> Enviroment  -> start program at logon: not working

### ISSUE THREAD

**Issue by joealbertvp** [binarymaster/rdpwrap#15]
Hi, this is a great software, just discovered that doesnt works the start program at logon, is there anyway to provide support to this?. Thanks

**Comment by binarymaster** [comment]
Hello.

I know about this issue though I don't know the solution for it.

Also I think if this issue will be resolved, that will be resolved too:
https://github.com/binarymaster/rdpwrap/issues/13

**Comment by binarymaster** [comment]
Issue resolved.
> https://github.com/binarymaster/rdpwrap/issues/13#issuecomment-77651843
