### ISSUE TITLE
Simple change so that you just have to double-click on install.bat

### ISSUE THREAD

**Issue by mll0** [binarymaster/rdpwrap#17]
Hi there, thanks for the precious tool.

You may do these simple changes to install.bat and uninstall.bat, so that when you double-click on theses batch files, they will work too :

* install.bat, line 2:
`    "%~dp0RDPWInst" -i`

* uninstall.bat, line 2:
`    "%~dp0RDPWInst" -u`

**Comment by binarymaster** [comment]
Very good idea!

I will modify batch files in the next release. Thanks!

**Comment by binarymaster** [comment]
Done.
