### ISSUE TITLE
Strange intermittent "hanging" issue

### ISSUE THREAD

**Issue by LocutusX** [binarymaster/rdpwrap#18]
Sadly I had to uninstall RDPWrap due to a strange intermittent "hanging on bootup" issue.
It was such a strange issue and very hard to isolate that RDPWrap was somehow causing it - but after uninstalling the wrapper, all is well now.
Basically, upon bootup & first login, a strange hanging effect was noticed in Windows 7 SP1 x64. Event viewer indicated the following errors whenever this phenomenon occurred:
- A timeout (30000 milliseconds) was reached while waiting for a transaction response from the NlaSvc service.
- A timeout (30000 milliseconds) was reached while waiting for a transaction response from the CryptSvc service.
- The server {F9A874B6-F8A8-4D73-B5A8-AB610816828B} did not register with DCOM within the required timeout.

(the third error's CLSID refers to "Terminal Services Connection Manager Class")

It's not clear to me *why* RDPWrap was causing these issues, but since RDPWrap touches each of the 3 services mentioned above, I thought there might be a connection. After uninstalling RDPWrap I am no longer getting this behaviour.

**Comment by binarymaster** [comment]
1. Try to add rdpwrap.dll to your antivirus exclusions
2. Try to use this command to isolate RDP Wrapper from other shared services:
sc config TermService type= own

**Comment by LocutusX** [comment]
I confirm that adding rdpwrap.dll to antivirus exclusions (in this case, Microsoft Security Essentials) has fixed the problem. No more strange hanging/freezing, even after multiple reboots.

Perhaps it will be a good idea to add this as a "known issue" to the Readme?

**Comment by binarymaster** [comment]
Good idea, I'll do it on the next release.
