### ISSUE TITLE
Slow RDP Win7 connection into Win8 computer: NOT a problem with RDPWrapper

### ISSUE THREAD

**Issue by EliezerBee** [binarymaster/rdpwrap#19]
In case it wasn't clear enough from the title line - this is **not** an issue with RDP Wrapper.  I've been trying to get the RDP connection from my Win7 desktop to my Win8 desktop quicker - it's been really slow.  I've tried several things - and most recently this:

http://superuser.com/questions/515180/rdp-connection-from-windows-7-8-to-server-2012-is-slow/571750#571750

Will that interfere with the (*awesome!*) functionality of RDP Wrapper?

Thanks,
Eliezer

**Comment by binarymaster** [comment]
Well, I think this setting will not conflict with RDP Wrapper functionality.
