### ISSUE TITLE
Win10 TP3 Build9926 not work

### ISSUE THREAD

**Issue by widewing** [binarymaster/rdpwrap#21]
Hi, I upgraded my system to Win10 Build9926(x64) and found this is not working. Then I copied the content of rdpwrap.ini from the latest code to local, restarted system and then the entire remote desktop service refused to start.

RDPConf.exe prompt:
Wrapper state: Installed                 ver. 1.5.0.0
Service state: Stopped                   ver. 10.0.9926.0
Listener state: Not listening           [fully supported]

Is the Win10TP3 version still in developing?

**Comment by binarymaster** [comment]
It's supported, you're doing something wrong.

See https://github.com/binarymaster/rdpwrap/issues/16#issuecomment-71398025

**Comment by widewing** [comment]
Can you please suggest me how do it right?

**Comment by binarymaster** [comment]
Well, see also this: https://github.com/binarymaster/rdpwrap/issues/16#issuecomment-76791379

**Comment by widewing** [comment]
Yes, I followed exactly the steps in the video, but the service just refuse to start...
