### ISSUE TITLE
 kb2574819 / kb2592687 / kb2830177 (installed on the client) Black screen

### ISSUE THREAD

**Issue by vandenk** [binarymaster/rdpwrap#22]
Hello,

I have a problem with Win7 (all versions) / RDPWrapper 1.5.
With kb2574819 / kb2592687 / kb2830477 (installed on the client)
if I conect me to a windows 7 pc (with or without these update) and I select in the rdp client (experience settings: LAN> 10Mbit + all boxes checked / and DisplaySettings: full screen).
When I minimize the window and restore then : I have a black screen ... I have to deconecter me and reconnect ...
If the client has not these update all works well ...

there is a solution ?

First Test :
PC1 (server) with RDPWrapper 1.5 without kb2574819 / kb2592687 / kb2830477 : Win7 x64 Ultimate
PC2 (client) without RDPWrapper with kb2574819 / kb2592687 / kb2830477 : Win7 x86 Starter

Second Test :
PC1 (server/client) with RDPWrapper 1.5 and with kb2574819 / kb2592687 / kb2830477 : Win7 x64 Ultimate
If I conect on 127.0.0.2 I have the same issue ...

**Comment by vandenk** [comment]
How do you do for the loopback address (127.0.0.1) Works ?
http://stascorp.com/images/rdpwrap/Win7ST.png

**Comment by vandenk** [comment]
Ok after more test it's a Windows 7 problem (with kb2574819 / kb2592687 / kb2830177) ...

Test 3 (same problem) :
PC3 (server) without RDPWrapper / without kb2574819 / kb2592687 / kb2830177 : Win7 x64 

Ultimate
PC2 (client) without RDPWrapper with kb2574819 / kb2592687 / kb2830177 : Win7 x86 Starter

Test 4 (same problem) :
PC4 (server) without RDPWrapper / without kb2574819 / kb2592687 / kb2830177 : Win7 x86 

Ultimate
PC2 (client) without RDPWrapper with kb2574819 / kb2592687 / kb2830177 : Win7 x86 Starter

Test 5 (same problem) :
PC3 (server) without RDPWrapper / without kb2574819 / kb2592687 / kb2830177 : Win7 x64 

Ultimate
PC4 (client) without RDPWrapper / with kb2574819 / kb2592687 / kb2830177 : Win7 x86 

Ultimate

Test 6 (same problem) :
PC1 (server) with RDPWrapper / without kb2574819 / kb2592687 / kb2830177 : Win7 x64 

Ultimate
PC4 (client) without RDPWrapper / with kb2574819 / kb2592687 / kb2830177 : Win7 x86 

Ultimate

Sometimes it works one or two times but if you insist, or that we pass in windowed mode : black screen ..

**Comment by binarymaster** [comment]
I think this issue is related to Windows Terminal Server or Client, but not to RDP Wrapper, so I close this issue.

However if you find the solution for this, you may post it here.

**Comment by vandenk** [comment]
Yes ! Ok
I wait for new Windows updates ...
But how do you do for the loopback address (127.0.0.1) Works ?
http://stascorp.com/images/rdpwrap/Win7ST.png

**Comment by binarymaster** [comment]
I used Windows 7 (without SP1) to make this screenshot.

If client doesn't connect 127.0.0.1, you may try 127.0.0.2

**Comment by vandenk** [comment]
Ha Ok, 

I knew for 127.0.0.2, 127.0.0.3 ...
But for 127.0.0.1 you have to patch mstscax.dll
http://www.remkoweijnen.nl/blog/2009/01/16/windows-xp-x64-terminal-server-patch-part-2-optional/
I had tested it on XP x86 SP3 it's working ... I also patch explorer.exe to get the stop button in the start menu ...
Apparently for 127.0.0.1 it also works for Win7.
By cons for explorer.exe it does not work for Win7 ...

Original explorer.exe patch (XP x86 SP3) : 
Okay I check out if that can be enable by any registrysetting and saw that there are none.
Well so the only way(beside the these nice workarounds :) ) is to patch Explorer.exe
So here are the Search & Replace Pattern for the patch:

Patch Pattern #1
85 C0 75 1D 6A 1B
85 C0 75 00 6A 1B
Patch Pattern #2
85 C0 75 70 53
85 C0 75 00 53

... so open explorer.exe in your favourite Hexeditor and search and replace the patterns.
Yes you have to change two place to get the Shutdown button back in the Terminalserver.
This was the only clean way to patch.
Ah yes to save change explorer.exe that is in use do the following:
Rename explorer.exe to explorer.org
then copy explorer.org to explorer.exe.
