### ISSUE TITLE
RDPWrap x64 fails to load INI file

### ISSUE THREAD

**Issue by Damoz101** [binarymaster/rdpwrap#23]
Sorry if this isn't the place to ask but ive been using this for a long time and now its doing my head in

Currently running 
Windows 10 Technical Preview
Builld 10041

I have RD-Clip installed with the latest .ini however it just doesn't do it.
I'e tried uninstall reinstall soooo many times 

I still get the other user is logged in error message.

Have attached config and error screen. 

Love you work appreciate it.

![rdp](https://cloud.githubusercontent.com/assets/11671508/6858267/f687e8d0-d471-11e4-8cad-071082a885d5.PNG)
![rdp1](https://cloud.githubusercontent.com/assets/11671508/6858272/fcab69f8-d471-11e4-9ff4-82bed1fbcc71.PNG)

**Comment by binarymaster** [comment]
It seems to be a known issue, that rdpwrap x64 can't load INI file.

We're working on it.

**Comment by lkraav** [comment]
I'm also not getting the current latest release working on 10030. Has WinX TP compatibility been solved?

**Comment by binarymaster** [comment]
Build 10130 isn't researched yet (there are no sections in INI file).

I'm waiting for final release in July.

**Comment by BigApple1988** [comment]
Это настолько элементарно, что даже обидно. перелопатив половину кода, и поняв что парсер Ini-файла видит файл как одну строку - перевел rdpwrap.ini в Windows-формат отображения строк (\r\n против \n). Все заработало (правда на библиотеке из последних исходников, на более старых не проверял).

**Comment by binarymaster** [comment]
Ого, так вот где собака зарыта! Спасибо!

**Comment by binarymaster** [comment]
As said BigApple1988, for x64 version, the INI file should be in Windows `<CRLF>` line format (Unix `<LF>` format is not supported).

**Comment by binarymaster** [comment]
WisdomWolf helped with adding a workaround, I hope this will help :)

https://github.com/binarymaster/rdpwrap/commit/f534a1c8fcf7a5709b6d251888671981e2c6d2aa

**Comment by GregAce** [comment]
Hi
same issue here with Windows 10 RTM Enterprise. Workaround does not help.

**Comment by binarymaster** [comment]
New version includes update feature, which downloads latest INI file from repository with correct line-break format.
