### ISSUE TITLE
Installation failing on Win 7

### ISSUE THREAD

**Issue by SebNYD** [binarymaster/rdpwrap#25]
Hello,

Installation is failing on Windows 7 (French fresh install and fully up to date) as you can see :

[*] Installing...
[*] Terminal Services version: 6.1.7601.18637
[+] This version of Terminal Services is fully supported.
[*] Configuring TermService...
[*] Starting TermService...
[-] StartService error (code 1068).
[-] Failed to set up TermService. Unknown error.

Any suggestion as to how I could overcome the issue ?

Thanks,

Seb

**Comment by avonwyss** [comment]
Error 1068 is "The dependency service or group failed to start.". Check for any disabled/malfunctioning dependencies of TermService:
![image](https://cloud.githubusercontent.com/assets/1014766/6986107/6dd9e5dc-da3a-11e4-8861-e284c48264f4.png)
