### ISSUE TITLE
install.bat-uninstall.bat & UAC

### ISSUE THREAD

**Issue by Sta2s** [binarymaster/rdpwrap#27]
If UAC is enabled - there is no other way to install RDPWrap than:
1) launch elevated cmd
2) change dir to rdpwrap folder
3) execute install.bat

to fix this one line must be changed in install.bat:
```batch
RDPWInst -i
```
to
```batch
%~dp0RDPWInst -i
```
and in uninstall.bat
```
RDPWInst -u
```
to
```
%~dp0RDPWInst -u
```

renewed files will work from windows explorer as expected and there will be no need in 1&2

**Comment by binarymaster** [comment]
Duplicate issue of https://github.com/binarymaster/rdpwrap/issues/17

This will be fixed in future release. Thanks.
