### ISSUE TITLE
can RDPWrap allow me to take over the existing RDP / console session ?

### ISSUE THREAD

**Issue by ahmgithubahm** [binarymaster/rdpwrap#28]
This isn't an issue with RDPwrap, but it might be an enhancement request. :-)

I have a VM that is running Win 8.1 Enterprise x86, and would like to be able to RDP to this box, and carry on from where I left off, last time I was using it, either RDP or console.  Currently, making a normal RDP connection (no RDPwrap installed), making a new connection always logs off the existing (console or RDP) session first.  Does anyone else see that as well?

**Comment by avonwyss** [comment]
Have you tried using the console session?
`mstsc /admin`

**Comment by ahmgithubahm** [comment]
Hi.  Thanks for the suggestion.  It makes no difference unfortunately.

**Comment by binarymaster** [comment]
If you want to connect to console session automatically, use option "Single Session Per User".
Another way is to use Windows Task Manager (Users tab) to connect console session.
