### ISSUE TITLE
Will Windows 10 present a problem for RdpWrap?

### ISSUE THREAD

**Issue by EliezerBee** [binarymaster/rdpwrap#31]
I was reading an article on Forbes:

http://www.forbes.com/sites/gordonkelly/2015/06/16/why-windows-10-upgrades-automatically-on-windows-7-and-windows-8/

which said:
*In short: every Windows 10 Home upgrade is installed automatically, with no option to decline it.*

Might that squash the terrific functionality of RDP Wrap?

**Comment by UksusoFF** [comment]
First: You can remove WinX updater. https://www.google.ru/search?q=GWX%20remove
Second: RDP Wrap works in WinX

**Comment by binarymaster** [comment]
If Windows 10 release wouldn't change the internal structure of terminal services, there will be the same as with other new updates.

**Comment by EliezerBee** [comment]
I am looking to (eventually) migrate to WinX, not avoid it. I was wondering
if the potential is now greater that RDP Wrap will be broken - perhaps
intentionally by Microsoft - with no way to get it working again.

**Comment by binarymaster** [comment]
Added Windows 10 (build 10.0.10240.16384) to support, I think there will be no problem adding new updates.
