### ISSUE TITLE
Windows 10 10240

### ISSUE THREAD

**Issue by tholden** [binarymaster/rdpwrap#33]
Now Windows 10 has hit RTM, it would be great to have a new release supporting it.

Thanks

**Comment by binarymaster** [comment]
INI file updated, please test it.

**Comment by binarymaster** [comment]
Tested on Win 10 Enterprise x86 (in VirtualBox 5), works without issues.

**Comment by binarymaster** [comment]
Also works on Win 10 Enterprise x64.

**Comment by tholden** [comment]
Thanks a lot. Much appreciated. Confirmed working on Win 10 Pro x64.

**Comment by Herjar** [comment]
I can't get this to work no matter what I try on Win 10 Pro x64 (10240)

**Comment by binarymaster** [comment]
@Herjar
You're doing something wrong... follow this video tutorial:
http://www.youtube.com/watch?v=W9BpbEt1yJw

**Comment by Herjar** [comment]
That's what I was trying, but I downloaded everything over again now to test.
It installs fine and I get it running, with no support.
Then I try to change the rdpwrap.ini file and I am not allowed to cut/paste or delete the file in Program Files. I get the message: "file is open in Cryptographic Services".
I can however copy/paste over it for some reason. When I do that and try to restart with "RDPWInst.exe -r" it will not start again and I end up with this: http://i.imgur.com/W236RWK.png

Everything looks ok when I run the command, but the service does not start:
RDP Wrapper Library v1.5
Installer v2.2
Copyright (C) Stas'M Corp. 2014

[*] Restarting...
[*] Configuring TermService...
[*] Starting TermService...
[+] TermService found (pid 11796).
[*] Shared services found: CryptSvc, Dnscache
[*] Terminating service...
[*] Starting CryptSvc...
[*] Starting Dnscache...
[*] Starting TermService...
[+] Done.

I followed every step in the video. Any idea what could be wrong?

**Comment by binarymaster** [comment]
Hm... maybe it's related to this issue: https://github.com/binarymaster/rdpwrap/issues/23

Try these steps:
1. Disable Terminal Services
`sc config TermService start= disabled`
2. Restart your PC
3. Replace old INI file with new one (since termsrv is disabled, file shouldn't be locked)
4. Enable and start Terminal Services
`sc config TermService start= auto`
`sc start TermService`

**Comment by Herjar** [comment]
Yea then I can replace rdpwrap.ini but I still cannot start the service after changing the file. 

I checked the event viewer and found these:
1.  The Remote Desktop Services service terminated unexpectedly. It has done this 20 time(s).
2.  The Cryptographic Services service terminated unexpectedly. It has done this 18 time(s).
3.  Faulting application name: svchost.exe_CryptSvc, version: 10.0.10240.16384, time stamp: 0x559f38cb
Faulting module name: rdpwrap.dll, version: 1.5.0.0, time stamp: 0x5488aa5a
Exception code: 0xc0000005
Fault offset: 0x0000000000002953
Faulting process ID: 0x1730
Faulting application start time: 0x01d0c127a7687915
Faulting application path: C:\WINDOWS\system32\svchost.exe
Faulting module path: c:\program files\rdp wrapper\rdpwrap.dll
Report ID: 3d42bbe3-5153-4d03-a441-584cf1b53398
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Herjar** [comment]
Sorry forgot to mention it's running installed on my PC, not VM.

**Comment by binarymaster** [comment]
Try to do this:
1. `sc config TermService type= own`
2. If you have antivirus software, try to add rdpwrap.dll to exclusions
3. Create file `rdpwrap.txt` in the root of system disk (for example `C:\rdpwrap.txt`)
4. Restart PC
5. Check contents of `rdpwrap.txt` log file

**Comment by Herjar** [comment]
Ok I tried that now, but the service still does not start. Got this in the txt file:

<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFBE66123B8] bServerSku = 1
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFBE5910000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...

**Comment by binarymaster** [comment]
Very strange... actions in the provided log were completed in wrong order.

@FusixGit I don't know how could this happen.

**Comment by UdoBaumann** [comment]
I just installed Windows 10 today (final) and having exact the same issue....

**Comment by hooges8** [comment]
Same issue with Windows 10 here (final) today:

Event viewer shows the Remote Desktop Services service terminated unexpectedly, as well as cryptographic services, dns, network location awareness.

Yes, I updated the INI file with the most recent version.  Listening showed not listening in config, but fully supported.

**Comment by flauschi82** [comment]
Same here - Not working with Windows 10 final.

Exception in rdpwrap.dll, Version 1.5.0.0
Code: 0xc0000005, Offset: 0x0000000000002953

The version of the TermService is 10.0.10240.16384

**Comment by alfred0** [comment]
thanks for all the help binarymaster - i hope i can provide any help to my best abilities to solve this for everyone ere experiencing same issue

**Comment by hirolash** [comment]
I'm running Windows 10 Home. I installed RDPWrap v1.5 and updated the rdpwrap.ini file. 
When I restarted rdpwinst I get a couple of StartService error (code 1056) in the CMD window and in the RDP Wrapper Configuration the Listener state is Not Listening.

This is my first time working with RDPWrap and I'm not too knowledgeable with this type of installation. Any help would be greatly appreciated.
![capture](https://cloud.githubusercontent.com/assets/13588346/9016980/0b24352a-37a3-11e5-840f-c6bf8fe7d5bd.JPG)

**Comment by alfred0** [comment]
hirolash - restart the machine i did that and it came back. i also turned off shadowing but i dont think that matters

**Comment by hirolash** [comment]
Thanks for the reply Alfred0,
I disabled Shadowing and restarted the computer, Listener State is still Not Listening. 

Would it make a difference if I replaced the termsrv.dll and rdpclip.exe files with ones from a Windows 10 Pro computer? I have not done that but I have a Windows 10 Pro computer available to me and I can copy the files if that would help fix the problem.

**Comment by alfred0** [comment]
hirolash i didnt have to do any of that.. all i did was run the install in elevated command prompt then restarted.. 
![mine](https://cloud.githubusercontent.com/assets/13570306/9017808/edead51e-37a6-11e5-983b-0ebd8945ffb1.PNG)

**Comment by hirolash** [comment]
gompf01 figured out the solution, I needed to add an extra blank line at the bottom of the ini file. Thank you for your help alfred0, I would have given up if you hadn't responded and keep me going.

**Comment by Stephan35** [comment]
Hello,
Tried on windows 10 with admin right , here is print screen.
can't get it working.
![winver](https://cloud.githubusercontent.com/assets/16188172/11624285/1c26c10e-9cd3-11e5-9a85-61ef03c87562.png)
![rdpwrapper](https://cloud.githubusercontent.com/assets/16188172/11624286/1c2ce944-9cd3-11e5-84f8-7f4369788e20.png)

Thanks for reply
Best regards.
