### ISSUE TITLE
Windows 10 Home

### ISSUE THREAD

**Issue by dragon2611** [binarymaster/rdpwrap#34]
Is there any possibility of getting this working on windows 10 home? (which is what my tablet seems to be running)

RDPconf shows the listening state as Not Listening [Not Supported] after installation, prior to install it just says Not listening

**Comment by binarymaster** [comment]
Did you updated the INI configuration file?

**Comment by dragon2611** [comment]
Opps I hadn't

Although now I can try to connect to the tablet, get prompted to authenticate but I never seem to actually get a session load, the RDP window just dissapears, I've disabled shadowing in RDP config.

Also Firewall/Antivirus is off on the tablet

**Comment by binarymaster** [comment]
RDP Checker works or not?

**Comment by dragon2611** [comment]
It goes connecting then immediately to disconnecting and closes

**Comment by binarymaster** [comment]
Please provide log file (create rdpwrap.txt in the root directory of system disk, `C:\rdpwrap.txt` for example), then restart your PC.

**Comment by dragon2611** [comment]
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x72690000
SvcMain:    termsrv.dll+0x44220
SvcGlobals: termsrv.dll+0x51CE0
Version:    10.0.10240.16384
Freezing threads...
Caching patch codes...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x72753F74] bServerSku = 1
SLInit [0x72753F7C] bRemoteConnAllowed = 1
SLInit [0x72753F60] bFUSEnabled = 1
SLInit [0x72753F68] bAppServerAllowed = 1
SLInit [0x72753F70] bMultimonAllowed = 1
SLInit [0x72753F64] lMaxUserSessions = 0
SLInit [0x72753F78] ulMaxDebugSessions = 0
SLInit [0x72753F6C] bInitialized = 1
<<< CSLQuery::Initialize

**Comment by binarymaster** [comment]
It seems everything is good. I'll try to install Windows 10 Home myself and check it.

**Comment by apg1980** [comment]
today i've upgradet to windows 10 home, and i get an error in the config app that no rdpwrap is not listening and not supported.

i have created a antivirus exception an a firewall rule.

nothing works, what can i do to make it fly?

best regards

**Comment by dragon2611** [comment]
Replace the rdpwrap.ini with a newer one found inthe res folder on github

There's a tutorial on youtube I think I'd link it but I'm on a mobile

It will make it show supported after but it will be interesting to see if it works

Sent by MailWise<http://www.mail-wise.com/installation/4>

**Comment by XperianPro** [comment]
Just tested on Windows 10 Pro,it says it's fully supported but it does not allow more than one user to log in at the same time.

**Comment by binarymaster** [comment]
@XperianPro read comments:
https://github.com/binarymaster/rdpwrap/issues/36#issuecomment-125941538
https://github.com/binarymaster/rdpwrap/issues/23#issuecomment-125948459

**Comment by XperianPro** [comment]
Now just doesn't work http://pasteboard.co/2kiO2YI4.png
and log
'Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFA99190000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFA992823B8] bServerSku = 1
'

**Comment by binarymaster** [comment]
Software exception is somewhere...

**Comment by XperianPro** [comment]
I feel really stupid,this is whole log if you were referencing on that it was incomplete. Now could this be something on my end or some unresolved bug? Thanks for help.

**Comment by binarymaster** [comment]
Theoretically it can be anything. Try to do these things:
1. Disable AntiVirus (or add rdpwrap.dll to exclusions)
2. Configure service as type own
`sc config TermService type= own`

**Comment by binarymaster** [comment]
I confirm that Windows 10 Home disconnects session, although the listener and port are working. This needs to be researched.

**Comment by binarymaster** [comment]
I accidentally... a wrong x86 LocalOnly offset xD
https://github.com/binarymaster/rdpwrap/commit/b9149eef023c309644785ddb566c0a71a45ba153

Now it works. @dragon2611 update your INI file :)

**Comment by dragon2611** [comment]
I can confirm works, that makes it a lot easier to do the updates for various apps on the tablet rather than having to fumble around with that stupidly small touchscreen i can now RDP in from another machine.

Don't see why they don't allow RDP by default esp on tablets.
