### ISSUE TITLE
Windows 10 Pro Insider 10240

### ISSUE THREAD

**Issue by BigApple1988** [binarymaster/rdpwrap#35]
Не получается запустить RDPWrapper.

ini-файл заменен на новый (от 17.07.2015), RDPConf показывает, что все ок. 
![image](https://cloud.githubusercontent.com/assets/9944869/8931985/9d86a38c-3553-11e5-8f7b-0a2363ce10a8.png)

лог:

```
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFA36000000
SvcMain:    termsrv.dll+0x000000000000CDF0
SvcGlobals: termsrv.dll+0x00000000000345A0
Version:    10.0.10240.16384
Freezing threads...
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> SvchostPushServiceGlobals
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
```

**Comment by binarymaster** [comment]
Это лог откуда?

**Comment by BigApple1988** [comment]
сорри, не из того файла достал))
поправил

попытки загрузиться в логе - это со старым ini-файлом, последние две строки - с новым, после перезагрузки

**Comment by binarymaster** [comment]
Очевидно, дубликат этой проблемы: https://github.com/binarymaster/rdpwrap/issues/23

Уже давно пытаемся решить её, но она возникает только у единиц - причина пока не ясна.

**Comment by binarymaster** [comment]
Вообще говоря, в идеале было бы здорово установить среду разработки Microsoft Visual Studio 2013, и в режиме отладки протрассировать проблемные места...

**Comment by BigApple1988** [comment]
у меня 2015 стоит, только я не пойму к какому процессу цепляться?

**Comment by binarymaster** [comment]
К svchost.exe
А PID процесса можно узнать, набрав tasklist /svc и найти там TermService

**Comment by BigApple1988** [comment]
ок, я никогда не отлаживал дллки. что делать дальше? или могу дать удаленку, если хотите

**Comment by binarymaster** [comment]
У меня сейчас времени свободного маловато, жду возвращения @FusixGit (он писал x64 библиотеку), надо к нему обращаться

**Comment by BigApple1988** [comment]
хорошо, дайте мне знать. я со своей стороны тоже попробую с гугло-помощью самостоятельно покрутить библиотеку
