### ISSUE TITLE
Windows 10 Enterprise 10240.16384

### ISSUE THREAD

**Issue by kolomparrudi** [binarymaster/rdpwrap#36]
Hi,

I have installed rdpwrap to Windows 10 enterprise. After upgrading ini file rdpconf said fully supported and everything is working fine.
But when I try it it won't allow more than one active rdp session.
Tried to find the log file, but there is no rdpwrap.txt on the root of the c:
Also tried to compile the latest x64 rdpwrap.dll, but the result is the same.

Any idea?

madar

**Comment by binarymaster** [comment]
You need to create log file manually, then restart TermService

**Comment by EliezerBee** [comment]
Is this necessary on all versions of Windows 10 or just Enterprise?

**Comment by binarymaster** [comment]
>Is this necessary on all versions of Windows 10 or just Enterprise?
Yes, RDP Wrapper doesn't create log file. It writes only if it exists.

**Comment by kolomparrudi** [comment]
Created the log file, restarted it, but log only contains this:

Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini

**Comment by EliezerBee** [comment]
Could that be changed?

**Comment by binarymaster** [comment]
> Could that be changed?

Of course, but it isn't necessary IMHO. Feel free to fork and modify source code.

> Created the log file, restarted it, but log only contains this

Seems to be a duplicate issue of https://github.com/binarymaster/rdpwrap/issues/23
Please check that your INI file has Windows <CRLF> line format (x64 version doesn't support Linux <LF> format).

**Comment by EliezerBee** [comment]
I'm confused, because when I first installed it, I never manually created a
log file,yet it worked correctly.

**Comment by kolomparrudi** [comment]
Thanks!
Converting the ini with unix2dos solved the problem!

**Comment by binarymaster** [comment]
> I'm confused, because when I first installed it, I never manually created a
log file,yet it worked correctly.

Seems to be a bug...
https://github.com/binarymaster/rdpwrap/blob/master/src-x86-x64-Fusix/RDPWrap.cpp#L97
`OPEN_ALWAYS` needs to be changed to `OPEN_EXISTING`.

> Converting the ini with unix2dos solved the problem!

Excellent! :)
