### ISSUE TITLE
Windows 10 "not listening"

### ISSUE THREAD

**Issue by eXaminator** [binarymaster/rdpwrap#40]
Hi, I just installed the rdpwrap with the current INI (using the youtube video guide). When I run the Config tool everything is green except the listener state which says "not listening".

I'm not sure what information to add to help solve this problem, so I'll just throw in some infos I can find:
- I upgraded Windows 7 Home Premium to Windows 10 Home
- Version next to wrapper state: 1.5.0.0
- Version next to service state: 10.0.10240.16384
- Port is 3386
- I verified that "Remotedesktop" is allowed in the Firewall rules
- I (obviously) can't connect using the check tool

I'm not sure if this is a bug or if I'm doing something wrong. Any help would be appreciated. If I can get any more data to help with this I'd be glad to provide them (given some directions where to retrieve them).

**Comment by binarymaster** [comment]
This is related to one of these two issues:
1. https://github.com/binarymaster/rdpwrap/issues/23#issuecomment-125948459
2. https://github.com/binarymaster/rdpwrap/issues/39
