### ISSUE TITLE
 it doesn't work in Windows 10 Home (RTM)

### ISSUE THREAD

**Issue by szpebble** [binarymaster/rdpwrap#41]
Listener state:NOt listening [not supported]

**Comment by binarymaster** [comment]
Which termsrv.dll version is?

**Comment by hirolash** [comment]
Windows 10 Home: 
termsrv.dll - file version: 10.0.10240.16384

**Comment by binarymaster** [comment]
This version is fully supported, update your INI file.

Before posting a new issue, make sure that there is no related open or closed issues. And always check latest commits.
