### ISSUE TITLE
Win 10 with new config but ending up without wrapper session

### ISSUE THREAD

**Issue by dh3lix** [binarymaster/rdpwrap#42]
Hiya,

kinda lost in troubleshooting here - win 10 - wrapper 1.5 with new config installed fine and nicely but ending up like using no wrapper at all ...

diag stats...

![hypersnapx_01844](https://cloud.githubusercontent.com/assets/1379420/9015427/2df8ff4c-37c9-11e5-97b1-c38d01bbd5a7.jpg)

rdpwrap log...

![hypersnapx_01845](https://cloud.githubusercontent.com/assets/1379420/9015430/3572ab6a-37c9-11e5-9557-a4afded4d3fc.jpg)

No real clue how to troubleshoot further - any advice will do tho ^^

--rgds marcO

**Comment by binarymaster** [comment]
A duplicate issue of https://github.com/binarymaster/rdpwrap/issues/23 and https://github.com/binarymaster/rdpwrap/issues/39#issuecomment-126592057.
