### ISSUE TITLE
Listener State Not Listening

### ISSUE THREAD

**Issue by hirolash** [binarymaster/rdpwrap#43]
I'm running Windows 10 Home. I installed RDPWrap v1.5 and updated the rdpwrap.ini file. 
When I restarted rdpwinst I get a couple of StartService error (code 1056) in the CMD window and in the RDP Wrapper Configuration the Listener state is Not Listening.   

This is my first time working with RDPWrap and I'm not too knowledgeable with this type of installation. Any help would be greatly appreciated. 

![capture](https://cloud.githubusercontent.com/assets/13588346/9015855/1ea2f0d6-379a-11e5-9ae3-e107fa2a3b4e.JPG)

**Comment by binarymaster** [comment]
Duplicate issue of https://github.com/binarymaster/rdpwrap/issues/40
