### ISSUE TITLE
Listener stat = not listening - Windows 10 Home

### ISSUE THREAD

**Issue by ebny** [binarymaster/rdpwrap#45]
i installed successfully,  updated the ini (followed the youtube video https://www.youtube.com/watch?v=W9BpbEt1yJw) but when i restart the RDPWInst.exe i get this:

![image](https://cloud.githubusercontent.com/assets/13598654/9021265/f5b99b5e-37f6-11e5-9c9d-7e6a009cd787.png)

not sure what it could be..please help...

**Comment by hirolash** [comment]
I had this problem and a very helpful person named [gompf01](https://github.com/gompf01) figured out the solution. You need to add an extra blank line at the bottom of the ini file. 

![capture](https://cloud.githubusercontent.com/assets/13588346/9021557/d9f9a782-3815-11e5-847a-3c8351f1a0d9.jpg)

**Comment by binarymaster** [comment]
Duplicate issue of https://github.com/binarymaster/rdpwrap/issues/43 and https://github.com/binarymaster/rdpwrap/issues/40

See https://github.com/binarymaster/rdpwrap/issues/39#issuecomment-126592057

**Comment by ebny** [comment]
Works Thx!

**Comment by mhagens** [comment]
It's not clear where the location of this .ini file is

**Comment by mhagens** [comment]
This is what I have: http://matthagens.com/sandbox/2016-02-01_09-25-00.png

**Comment by binarymaster** [comment]
@mhagens see installation log, it does display full path to INI file.

@ebny according to your first screenshot in this thread, RDP protocol is just disabled, you need to set checkbox "Enable Remote Desktop Protocol" and click Apply. Curious that I didn't noticed it before. xD

**Comment by mhagens** [comment]
Clicking the "update.bat" actually got it to work: http://matthagens.com/sandbox/2016-02-01_09-33-02.png

Thanks for the super fast reply!

**Comment by cellomania** [comment]
In my case is still not solved.
Any other tip?
![0001 1](https://cloud.githubusercontent.com/assets/17168949/12964360/09b99b12-d050-11e5-94ab-f0b93fcc27f1.jpg)

**Comment by cellomania** [comment]
In my case isn't solved.
Any other tip?
![rdp](https://cloud.githubusercontent.com/assets/17168949/12964383/300d73ce-d050-11e5-8d7f-43b98caf7b70.JPG)

**Comment by cellomania** [comment]
Solved with these commands:
wdpinst.exe -u
wdpinst.exe -i
update.bat

**Comment by nickraz** [comment]
<p>Та же картина:</p>
<img src="http://i.imgur.com/nP4uMwZ.png" />
<p>Система: Win10 Home x64</p>

**Comment by nickraz** [comment]
Печально. Спасибо.

**Comment by Mattia86** [comment]
Me too: after the creative update I'm not able to manage my atom stick PC remotely, had to switch to Teamviewer for the moment.

**Comment by MikeSam06** [comment]
same as Mattia86.
my post had closed by binarymaster...
i always looking for the solution right now.

**Comment by dblbassman** [comment]
Kudos to binarymaster for supplying this great RDP patch for years free of charge.  I, too, hope that a fix for Win 10 Creator Edition will be forthcoming.  FWIW, I'd be happy to pay for it.  It would seem entirely reasonable to charge $5 or so for some sort of license.  Perhaps it would be an incentive for "the master" as it would compensate, if only modestly, for his time.

**Comment by LeoNatan** [comment]
Have the same issue on my Windows 10 Home.

**Comment by binarymaster** [comment]
@LeoNatan read README and #194.

**Comment by LeoNatan** [comment]
I saw that issue and the workaround after posting, thanks. Is there a reason that DLL is not installed during install.bat?

**Comment by binarymaster** [comment]
> Is there a reason that DLL is not installed during install.bat?

Feature not implemented in the installer yet.
