### ISSUE TITLE
do not support the Windows 10 pro

### ISSUE THREAD

**Issue by liuwenru** [binarymaster/rdpwrap#46]
can you write the using operation such as one exe

**Comment by binarymaster** [comment]
Update INI file manually or wait for the next release (I don't know when it will be, there are a couple of small bugs and unimplemented features).

**Comment by liuwenru** [comment]
how to change the ini file！i change the logfile path but it also do not work such as i say

**Comment by binarymaster** [comment]
See Tutorial videos section in the readme

**Comment by binarymaster** [comment]
Added update feature to the installer.
