### ISSUE TITLE
Terminal Services version: 10.0.10240.16384 not supported ?

### ISSUE THREAD

**Issue by KnuX** [binarymaster/rdpwrap#49]
Hi,

This is the install log : 
Installer v2.2
Copyright (C) Stas'M Corp. 2014

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.10240.16384
[-] This version of Terminal Services is not supported.
Send your termsrv.dll to project developer for support.
[*] Configuring TermService...
[*] Starting TermService...
[+] TermService found (pid 1116).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting CryptSvc...
[*] Starting Dnscache...
[-] StartService error (code 1056).
[*] Starting LanmanWorkstation...
[*] Starting NlaSvc...
[-] StartService error (code 1056).
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...
Ok.

[+] Successfully installed.

It's a clean install of Windows 10 Home French version. (How can I send you this file ?)

Thx

**Comment by AndrewSav** [comment]
Read the closed issues - there is a solution.
