### ISSUE TITLE
Listener state: Not listening not supported

### ISSUE THREAD

**Issue by moqiguzhu** [binarymaster/rdpwrap#51]
I follow the installation instruction:
- download the latest released RDP WRAPPER, version 1.5
- run the install.bat
- run the RDPCheck.exe -- failed
- run the RDPConf

I see that Windows 10 home edition has already been supported, where am I wrong?
Should I download the source codes and compile myself?

**Comment by bubbleguuum** [comment]
Confirming the same issue on Windows 10 Home.

**Comment by binarymaster** [comment]
Why you don't read closed issues?

**Comment by bubbleguuum** [comment]
Got it but why don't you make a download that just works to avoid the same issue being reported again and again and again ?

**Comment by binarymaster** [comment]
Indeed... v1.6 released! :)

**Comment by EliezerBee** [comment]
So does v1.6 now support running a session on one PC (under my username)
then continuing that same session (applications still running) from another
PC (again under my username)?

**Comment by binarymaster** [comment]
> So does v1.6 now support running a session on one PC (under my username)
then continuing that same session (applications still running) from another
PC (again under my username)?
No, see this issue: https://github.com/binarymaster/rdpwrap/issues/37

**Comment by EliezerBee** [comment]
I see in issue #37 <https://github.com/binarymaster/rdpwrap/issues/37> that
this has been around since Win8. I've been using it for exactly that on
Win8.1 for quite a while - never had an issue.

So please explain: if this does not work, what exactly *does* RDPWrapper
accomplish on Windows 10? Isn't that the whole point of it?... *(Confused.)*

**Comment by binarymaster** [comment]
I actually have none of these issues on my Windows 10 Virtual Machine, so I can't confirm nor refuse it... You have to test it yourself.

**Comment by aiugrivef** [comment]
Tested on Win 10 **Home** edition, both 32 and 64 bits, and indeed rdpwrap does nothing...
TermServ service is not even listening on 3389 port.

**Comment by binarymaster** [comment]
@aiugrivef 
Did you test latest v1.6 release?

**Comment by EliezerBee** [comment]
*Aiugrivef*, does it at least accomplish the following? If User A is
physically sitting at and using the "server" - can User B *concurrently*
access his own login on the server from another computer?

**Comment by binarymaster** [comment]
> does it at least accomplish the following? If User A is
physically sitting at and using the "server" - can User B *concurrently*
access his own login on the server from another computer?

Yes. See the latest screenshot in the README.md

**Comment by moqiguzhu** [comment]
Sorry to bother you.
It is the first time that I use issues. Before I post the issue, I have not noticed that there is a column called closed issues. 
Never happen next time.

**Comment by binarymaster** [comment]
Thanks :)
