### ISSUE TITLE
We should log all the windows updates that do not alter functionality

### ISSUE THREAD

**Issue by dav01it** [binarymaster/rdpwrap#53]
I've a commercial version of a "similar" of rdpwrap the problem is always the same: in some cases a windows update changes something, then rdp does not work until next software release.
Solution would be logging all the successfull (= not critical against rdpwrap) windows updates
would be great to "invent" a way to extract from a pc all the updates and send them automatically to a server. I like .net programming (because is fast very fast for RAD programming and works also in linux with mono), so I would like to collaborate  and help in that way if someone wants too!
I still do not use windows 10: i know there is another issue: you cannot avoid automatic updates unless you do not install a tool "https://support.microsoft.com/en-us/kb/3073930".

**Comment by binarymaster** [comment]
Hello.

Just open a new issue when a new unsupported build released.
