### ISSUE TITLE
How to create x64 and x86 version and publish it using Visual C++

### ISSUE THREAD

**Issue by cary1234** [binarymaster/rdpwrap#56]
I think I describe it in a detailed way here http://stackoverflow.com/questions/32281940/how-to-publish-or-export-x86-and-x64-c-version-of-rdpwrap?noredirect=1#comment52442417_32281940

**Comment by cary1234** [comment]
I think I describe it in a detailed way here http://stackoverflow.com/questions/32281940/how-to-publish-or-export-x86-and-x64-c-version-of-rdpwrap?noredirect=1#comment52442417_32281940

**Comment by binarymaster** [comment]
Solved.
