### ISSUE TITLE
Concurrent sessions sound

### ISSUE THREAD

**Issue by 2X3** [binarymaster/rdpwrap#57]
[Windows 8.1] When a user is logged in locally and is playing game at the moment [for example], if I connect to that computer through rdp with "sound stay on local computer" setting - local user loses sound completely and needs to log in again. I basically want this to work like it did on Windows 7 [It played sound from two users at the same time from same speakers].

**Comment by binarymaster** [comment]
It isn't RDP Wrapper issue, it's terminal services bug. So I can't fix it.
