### ISSUE TITLE
Windows 10 x64 Pro build 10532

### ISSUE THREAD

**Issue by Duken30** [binarymaster/rdpwrap#58]
Hello,

I just recently gave this a shot with Windows 10 Consumer Preview Build 10532. I can't seem to get it to work with this build. Any help would be greatly appreciated. I think it is because of the version of the termsrv.dll I have included a link to the dll.

http://wikisend.com/download/456260/termsrv.dll

**Comment by Daxby** [comment]
I have the same problem

**Comment by josefrvaldes** [comment]
I have the same problem but in the 10547 build. It installs but it keeps showing listening not supported.

**Comment by mac2000** [comment]
@binarymaster is there a way we can provide some more info to investigate that issue? got into same problem, just can not undertand from where to start

**Comment by jc93** [comment]
I have just encountered the same problem after loading Preview Build 10536; installs but showing listening not supported.

On another machine I have it running fine under 10.0.10240 (and very useful it is thanks, much appreciated).  Looks like 10240 will be replaced shortly.

**Comment by jc93** [comment]
My systems on Windows 10.0.10240 are now getting the push update to Version 1511 Build 10586.3.  Rdpwrap version 1.6 installs and completes "[+] Successfully installed", but with errors:

[*] Terminal Services version: 10.0.10586.0
[-] This version of Terminal Services is not supported.

[*] Starting Dnscache...
[-] StartService error (code 1056).

[*] Starting NlaSvc...
[-] StartService error (code 1056).

Shows listening not supported.

**Comment by dh3lix** [comment]
rdpwrap.ini needs to be updated to match w10 10586 release.

**Comment by josefrvaldes** [comment]
Are you sure? I have mi rdpwrap.ini updated since a few releases ago and it still doesn't work... And it hasn't been updated since 3 months ago.

**Comment by dh3lix** [comment]
I should have stated it this way "the rdpwrap.ini" must be updated and pushed to git - no actual matching ini is available at this time ;-)

**Comment by josefrvaldes** [comment]
ok! now I understand!! xDDD

**Comment by binarymaster** [comment]
Added support for build 10.0.10586.0, so build 10532 is already outdated.

**Comment by lotniak** [comment]
Ok so how can we install version that supports 10532 build?

**Comment by mac2000** [comment]
@lotniak seems that all you need to do is to replace ini file by this [one](https://github.com/binarymaster/rdpwrap/blob/master/res/rdpwrap.ini) it was [updated](https://github.com/binarymaster/rdpwrap/commit/741527eccd088d8363247bf492250e4bcc2b23dc#diff-1) and all should work, will check it tomorrow

**Comment by lotniak** [comment]
I've already done that. Restart and I'll update if it's okay.

**Comment by lotniak** [comment]
Works fine after restart. Thank you ;-)

**Comment by mac2000** [comment]
Confirming, I also have been able to run it successfully.Thank you.
