### ISSUE TITLE
Error in DLL file at logon

### ISSUE THREAD

**Issue by simonbjornes** [binarymaster/rdpwrap#60]
Hi.

Running Windows 10 Pro 64Bit fully updated.

While having Multi Session Per User active and the user logged in locally. (Maybe with a locked desktop)
I then login remotely with the same user and switch to the local user via task-manager.

The next time you try to login remotely or locally it just return "There was a error in the DLL file." after you type in user and password.

You can only click ok and then it returns to the password prompt.
A reboot is then necessary to get it back up and running.

**Comment by Tsaukpaetra** [comment]
As a side note, logging in as a new (not previously logged in) user still works, and the second user can close one of the sessions and allow recovery.

**Comment by afzalb** [comment]
I also have this. It appears to happen sporadically when there are multiple sessions open on a machine. Windows 10 changes that aren't taken into account by RDP Wrapper perhaps.

**Comment by simonbjornes** [comment]
You are able to avoid it by logging out/Cancel connection via Start Menu.

**Comment by binarymaster** [comment]
Duplicate issue of https://github.com/binarymaster/rdpwrap/issues/50.
