### ISSUE TITLE
legacy installer supports only x86

### ISSUE THREAD

**Issue by andrey-zibrov** [binarymaster/rdpwrap#61]
The legacy installer .bat file supports only x86 however dll file could be compiled for as x64 binary.
So what i'm doing wrong? i don't have pascal installed.Looks like it'll be better if all tools may assembled by one unique tool-chain.

**Comment by binarymaster** [comment]
Legacy .bat files are not used anymore.

Here is installer: https://github.com/binarymaster/rdpwrap/tree/master/src-installer

If you don't want to install full RAD Studio package, you may try to find the DCC compiler.
