### ISSUE TITLE
It's Installed but when check on Win 10 Home, not working.

### ISSUE THREAD

**Issue by benyaminl** [binarymaster/rdpwrap#62]
It's Installed but when check on Win 10 Home, not working. socket connection failed

**Comment by binarymaster** [comment]
Please provide more information, such as termsrv.dll version.

**Comment by gypsy3001** [comment]
I have the same problem. RDPCheck reports "Socket connection failed".

I don't know how to check termsrv.dll, but here is what dir reports:
10/29/2015  11:18 PM         1,033,216 termsrv.dll

I'm attaching what RDPConf shows.

![image1](https://cloud.githubusercontent.com/assets/16129539/11553194/16bc076e-9941-11e5-9299-6dbd433828df.png)

**Comment by gypsy3001** [comment]
I just ran the install again and noticed these lines:

[*] Terminal Services version: 10.0.10586.0
[-] This version of Terminal Services is not supported.
Send your termsrv.dll to project developer for support.

I wanted to attach termsrv.dll, but it won't let me attach it.

Following is the full install log:

Copyright (C) Stas'M Corp. 2015

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.10586.0
[-] This version of Terminal Services is not supported.
Send your termsrv.dll to project developer for support.
[*] Configuring TermService...
[*] Starting TermService...
[+] TermService found (pid 1212).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting CryptSvc...
[*] Starting Dnscache...
[-] StartService error (code 1056).
[*] Starting LanmanWorkstation...
[*] Starting NlaSvc...
[-] StartService error (code 1056).
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...
Ok.

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .

**Comment by gypsy3001** [comment]
Noticed there is an update.bat file. I ran it and now it works.

**Comment by jbest75** [comment]
I had the same issue. ran the update.bat and corrected the not listening issue. hope it helps!

**Comment by fewzhon** [comment]
any updates on this?

**Comment by binarymaster** [comment]
No.
