### ISSUE TITLE
Support for Windows 2012 non-R2 and R2

### ISSUE THREAD

**Issue by NetVicious** [binarymaster/rdpwrap#63]
Hi!

What about Windows 2012 (non-R2) termsrv.dll version 6.2.9200.17048
What about Windows 2012 R2 termsrv.dll version 6.3.9600.17415

If you need the DLLs I can send you they if you want.

Regards,

**Comment by mmehnert** [comment]
I've got Windows 2012 R2 termsrv.dll version 6.3.9600.17415 here and can't see any problems... Or will I get them once I reboot? ;-)

**Comment by NetVicious** [comment]
I don't know. I checked the hex bytes to crack the termsrv.dll and I didn't found they.

The other day I tried rdpwrap in a Windows 2012 R2 with termsrv.dll version 6.3.9600.17415 and all went perfect .

You can add it to the Supported Terminal Services versions.

Thanks for your work. Regards.

**Comment by binarymaster** [comment]
> 6.2.9200.17048
> 6.3.9600.17415

These builds already supported, it doesn't matter you have workstation or server edition.
