### ISSUE TITLE
No Symbols

### ISSUE THREAD

**Issue by DocMAX** [binarymaster/rdpwrap#64]
Hi, i have no function names.

http://www.directupload.net/file/d/4165/i97jyax2_jpg.htm

**Comment by Tsaukpaetra** [comment]
I would recommend contacting Microsoft, they supply the debug symbols for
Microsoft programs.

**Comment by DocMAX** [comment]
I had to install VC 2010 runtime.
I get symbols now, except for termsrv.dll from latest 10586 build.

**Comment by binarymaster** [comment]
Not a RDP Wrapper issue, closed.

Related issue here: https://github.com/binarymaster/rdpwrap/issues/65
