### ISSUE TITLE
Support for WIN10 Version: 1511 Build: 10586.3

### ISSUE THREAD

**Issue by tom4tom** [binarymaster/rdpwrap#65]
Hi,
after Updating yesterday, rdpwrap stop working!

ToM

**Comment by renatofelixalmeida** [comment]
Same problem for me.

**Comment by TiagoDM** [comment]
Same for me too... 

Tiago

**Comment by DocMAX** [comment]
Same for me

**Comment by jjkim74md** [comment]
Same for me

**Comment by binarymaster** [comment]
It will be same for everyone who using build 10586, because it isn't supported yet.

**Comment by DocMAX** [comment]
i'm trying this: https://www.youtube.com/watch?v=FiD86tmRBtk
but i get not symbols with 10586 termsrv.dll

**Comment by DocMAX** [comment]
Symbold are working for previous DLL, but not on 10586

**Comment by binarymaster** [comment]
Symbols are not required, because all instructions are described in KB file:
https://github.com/binarymaster/rdpwrap/blob/master/res/rdpwrap-ini-kb.txt (look at `HOW TO` comments)

Build `10.0.10586.0` has been added to support.
Use `RDPWInst -w` command to update.

![win10 10586](https://cloud.githubusercontent.com/assets/578406/11163890/9e551d54-8af1-11e5-9e57-0708cc1a08a6.png)

**Comment by tom4tom** [comment]
thx binarymaster for fixing! I'm not a developer - when do you bring out a new release?

**Comment by binarymaster** [comment]
I publish new releases when I do major changes in the apps. In other words, no need to make release for now.

Just use update function with the provided installer from the latest release.

**Comment by tom4tom** [comment]
ah, just RDPWInst -w !!! Cool  it works. THX, again

**Comment by renatofelixalmeida** [comment]
Its Working! Tanks

**Comment by jc93** [comment]
Excellent!  Thanks.

**Comment by DocMAX** [comment]
binarymaster thx! you hacker guys are the best!!!

**Comment by TiagoDM** [comment]
binarymaster thx!

2015-11-14 17:39 GMT+00:00 DocMAX <notifications@github.com>:

> binarymaster thx! you hacker guys are the best!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/binarymaster/rdpwrap/issues/65#issuecomment-156723643>
> .
>



-- 
________________________________________
Tiago Marques
