### ISSUE TITLE
Windows 10 Pro 10586 - termsrv.dll not supported, help

### ISSUE THREAD

**Issue by lotniak** [binarymaster/rdpwrap#66]
Hi

I've updated my Windows 10 Pro to the newest build and wrapper says - termsrv not supported. Can I fix this somehow fast? Dunno, maybe with ini or smth.?

Kind Regards

Lotniak

**Comment by binarymaster** [comment]
Duplicate of https://github.com/binarymaster/rdpwrap/issues/65
