### ISSUE TITLE
RDPWrap v1.6 doesn't support W10 November update.

### ISSUE THREAD

**Issue by TrueTenacity** [binarymaster/rdpwrap#69]
I have just finished upgrading my machine and I see now that I'm no longer able to remote into the machine. 

I tried uninstalling and re-installing RDPWrap, and I saw a message pop up about the terminal server version being unsupported.

**Comment by krzaczek** [comment]
run update.bat again .. it solved by problems

**Comment by TrueTenacity** [comment]
Ok, I'll give it a try...

**Comment by TrueTenacity** [comment]
Dude! Works perfectly now... awesome!
