### ISSUE TITLE
Uninstalling RDPWrap breaks RDP on Windows 10 Nov Update

### ISSUE THREAD

**Issue by Abrian** [binarymaster/rdpwrap#70]
I installed rdpwrap to test the functionality. I however want to log on as a user sitting in front of the computer. I then want to rdp from another computer with another user to get a different instance. This however logs the first user out. Is this possible?

I uninstalled rdpwrap but can now no longer use windows rdp as in the past. Why can't I connect?

**Some services fail to start...**

RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2015

[*] Notice to user:

By using all or any portion of this software, you are agreeing to be bound by all the terms and conditions of the license agreement.
To read the license agreement, run the installer with -l parameter.
If you do not agree to any terms of the license agreement, do not use the software. [] Installing... [] Terminal Services version: 10.0.10240.16384 [+] This version of Terminal Services is fully supported. [] Configuring TermService... [] Starting TermService... [+] TermService found (pid 1140). [] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc [] Extracting files... [+] Folder created: C:\Program Files\RDP Wrapper\ [+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini [+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll [] Configuring service library... [] Checking dependencies... [] Checking CertPropSvc... [] Checking SessionEnv... [] Terminating service... [] Starting CryptSvc... [-] StartService error (code 1056). [] Starting Dnscache... [-] StartService error (code 1056). [] Starting LanmanWorkstation... [] Starting NlaSvc... [-] StartService error (code 1056). [] Starting TermService... [] Configuring registry... [] Configuring firewall... Ok.
[+] Successfully installed.

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .

**Comment by Abrian** [comment]
RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2015

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.10240.16384
[+] This version of Terminal Services is fully supported.
[*] Configuring TermService...
[*] Starting TermService...
[+] TermService found (pid 1140).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting CryptSvc...
[-] StartService error (code 1056).
[*] Starting Dnscache...
[-] StartService error (code 1056).
[*] Starting LanmanWorkstation...
[*] Starting NlaSvc...
[-] StartService error (code 1056).
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...
Ok.

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .

**Comment by wuxuec** [comment]
The same problem, why.....so confused

**Comment by BFGoody** [comment]
No answer to uninstall and revert to native RDP working, but as for multi-session (having 2 users logged in simultaneously):

After installing RDPWrapper v1.6, execute update batch file in RDPWrapper v1.6 folder to get newest configuration file.

Worked for me, post if it works for you.
