### ISSUE TITLE
Can't get RDP Wrapper working

### ISSUE THREAD

**Issue by AdamGerthel** [binarymaster/rdpwrap#72]
Hi,

I'm running Windows 10 Pro x64, I've installed RDP Wrapper successfully but I still can't have multiple sessions:

![winrdp](https://cloud.githubusercontent.com/assets/1490370/11537905/a69aa7c2-991f-11e5-8b58-1be3a0f44314.png)

The firewall is open on the proper port, I've never altered the original dll file. The only thing that seems to be malfunctioning is that the conf program says:

> Listener State: `Listening` [Not supported ]

Any ideas was to why this is not working?

**Comment by hirolash** [comment]
Run update.bat from the command line (admin)

**Comment by AdamGerthel** [comment]
Thanks, solved! :+1: 

Btw, I just installed RDP Wrapper and have never used it before. Using an update after the first install is a bit unintuitive.
