### ISSUE TITLE
Windows Server TP4

### ISSUE THREAD

**Issue by Vova23** [binarymaster/rdpwrap#73]
В TP4 не работает
вот что пишет
RDP Wrapper Library v1.6

Installer v2.3

Copyright (C) Stas'M Corp. 2015

[*] Notice to user:

- By using all or any portion of this software, you are agreeing

to be bound by all the terms and conditions of the license agreement.

- To read the license agreement, run the installer with -l parameter.

- If you do not agree to any terms of the license agreement,

do not use the software.

[*] Installing...

[*] Terminal Services version: 10.0.10586.0

[-] This version of Terminal Services is not supported.

Send your termsrv.dll to project developer for support.

[+] TermService found (pid 840).

[*] No shared services found.

[*] Extracting files...

[+] Folder created: C:\Program Files\RDP Wrapper\

[+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini

[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll

[*] Configuring service library...

[*] Checking dependencies...

[*] Checking CertPropSvc...

[*] Checking SessionEnv...

[*] Terminating service...

[*] Starting TermService...

[*] Configuring registry...

[*] Configuring firewall...

The following helper DLL cannot be loaded: WCNNETSH.DLL.

Ok.

[+] Successfully installed.

______________________________________________________________

You can check RDP functionality with RDPCheck program.

Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .
вот файл termsrv.dll http://rghost.ru/8yMvWLxxr

**Comment by binarymaster** [comment]
Версия 10.0.10586.0 уже добавлена в поддержку, используйте `update.bat` для обновления ini-файла.
