### ISSUE TITLE
10.0.10586.0 Problem after restart

### ISSUE THREAD

**Issue by BFGoody** [binarymaster/rdpwrap#75]
Windows update received, listening state = no, paste newest INI, restart, then all status OK.

Computer restart, no connection available. Will post updates while troubleshooting.

2015-12-14 at Host executed uninstall batch file then install batch file from within RDPWrapper v1.6 folder, single session is now working, connection available.

2015-12-14 Execute update batch file from RDPWrapper v1.6 folder, multi-session working now.

So, I must have made error pasting newest INI, advise to not update by rewriting INI, just run update batch file in RDPWrapper v1.6 folder and things work good.

Thank you binarymaster, I use RPDWrapper to watch system performance in background when user complains system is running slow.

**Comment by nqs** [comment]
I'm also seeing this, but I dont have a fix yet.

**Comment by deliveli** [comment]
I discovered RDPWrapper yesterday and installed on my new PC with Win 10 home 64 bit. 
Version 1.6 It worked like a charm before Update for Windows 10 Version 1511 x64-based systems (KB3116278) hit my PC.. 

Now in the diagnostics of RDPConf it shows "Listener state: Not listening [not supported].

Something has changed with the Windows update. 

Version of termserv.dll is 10.0.10586.0 date 10/30/2015.

**Comment by deliveli** [comment]
It is working now after the update. Thank you

**Comment by robbsie** [comment]
How did you make it work again?

**Comment by deliveli** [comment]
Update.bat took care of it. 
I verified the firewall rules. There was another set of RDP port numbers in the AV firewall rules for some reason, one enabled (that I enabled before) and one not enabled. I enabled both and it worked. I am not sure if update added RDP rule to the firewall second time. AV is McAffee LifeSafe Internet Security.

**Comment by duncansmart** [comment]
Run install.bat and update rdpwrap.ini manually as I mentioned here: https://github.com/binarymaster/rdpwrap/issues/76#issuecomment-165589091
