### ISSUE TITLE
Install is not working

### ISSUE THREAD

**Issue by juanredondo** [binarymaster/rdpwrap#76]
Install is not working on windows 10 up to date. installation windows do nothing, and install.bat or update.bat run as admin is writing nothing on console.

![image](https://cloud.githubusercontent.com/assets/7248837/11843579/a2e81b64-a40a-11e5-91d7-c2e5cdc21954.png)

**Comment by robbsie** [comment]
Same here since the latest Win10 update.

**Comment by BFGoody** [comment]
As the Windows 10 Build 10586 update rolls out, I think a lot of us are going to have this issue. 
This has worked for me each and every time and it only takes a minute:

On each host, go to the folder you unpacked RDPWrapper v1.6 to.

Right-click on uninstall.bat, select Run as Administrator, continue until the process is completed.
Right-click on install.bat, select Run as Administrator, continue until the process is completed.
Right-click on update.bat, select Run as Administrator, continue until the process is completed. (must be connected to the Web to get update)
Right-click on RDPConf.exe, select Run as Administrator, Diagnostics should show Wrapper, Service and Listener State as good.

Being proactive does not seem to help, I have done this on Build 10240 machines prior to the 10586 update and connections fail as soon as the update comes through.

Wishing you success.

**Comment by juanredondo** [comment]
I'm following your step with no luck.

![image](https://cloud.githubusercontent.com/assets/7248837/11850564/5995780c-a42e-11e5-8c9f-a43360f8b454.png)

![image](https://cloud.githubusercontent.com/assets/7248837/11850577/6dbc4be4-a42e-11e5-8698-7d72e10dd536.png)


As administrator both times.

**Comment by duncansmart** [comment]
The rdpwrap.ini was updated in 741527e to support the latest Windows version 10.0.10586 that everyone has been getting recently. It doesn't seem that there has been an updated release that includes this, but it's easy to update by replacing `C:\Program Files\RDP Wrapper\rdpwrap.ini` with [this one](https://github.com/binarymaster/rdpwrap/raw/master/res/rdpwrap.ini) (right-click the link and Save-As) **after** you have tun the `install.bat` etc as outlined above.

You will need to stop the TermService process first before updating: from an **Administrator** command prompt run:

    taskkill /f /fi "services eq TermService"

Update rdpwrap.ini and then **reboot** or

    net start TermService
    net start DnsCache
    net start CryptSvc
    net start LanmanWorkstation
    net start NlaSvc

to get all/most the services that were in the same process going again. I now get the following when running RDPConf and it all appears to be working well

![image](https://cloud.githubusercontent.com/assets/576343/11882757/4cbc3926-a506-11e5-88ed-050a134f5e2d.png)

**Comment by robbsie** [comment]
Thanks, worked for me :+1:

**Comment by ViapVevsa** [comment]
BFGoody right click and run as administrator steps works for me.

**Comment by BFGoody** [comment]
juanredondo, I see you are working at the command prompt, I updated the TIP above to assist you further. I like seeing "Press the spacebar" to confirm the process has completed before moving to the next task. Strangely, sometimes they finish very quick and at other times it takes 7 or 8 seconds for the same task to complete on different machines.

**Comment by juanredondo** [comment]
Using las install.bat & update.bat as administrator solved the issue.

Thanks to everyone
