### ISSUE TITLE
Problem with update Windows 10.0.10586.17!

### ISSUE THREAD

**Issue by felipemb** [binarymaster/rdpwrap#77]
Hi,

The last sunday I had install the last update of Windows 10, exactly 10.0.10586.17 after the upgrade finish the software RDP Wrap don't work!

I try unistall and back to install but the problem persiste, attach a image of the error

Thanks for your attention!

Best regards!

![error](https://cloud.githubusercontent.com/assets/16559380/12116629/373d7998-b389-11e5-856f-44df8d16b0f0.png)

**Comment by AaronClover** [comment]
This is a duplicate of bug #77.

Run update.bat as an administrator and it should work.

**Comment by felipemb** [comment]
Thanks Aaron, was very easy the solution!

Have a good day!
