### ISSUE TITLE
Delphi 10 Seattle

### ISSUE THREAD

**Issue by fig2k4** [binarymaster/rdpwrap#81]
I built the git source in Delphi 10 and found a problem in RDPWInst.  It's probably relevant for older versions of Delphi too.

In CheckTermsrvProcess(), dwResumeHandle needs to be initialised to zero before calling EnumServicesStatusEx() otherwise the call fails, causing the installer to always fail.  It installs fine after this little fix.

**Comment by binarymaster** [comment]
Hello.

Can you provide a patch using pull request?

Thanks in advance!
