### ISSUE TITLE
RDP Wrapper Mirroring

### ISSUE THREAD

**Issue by mackib** [binarymaster/rdpwrap#83]
Hi!
Is it possible to get this great software to do mirroring? By this i mean se my acctuall screen on the client?

**Comment by binarymaster** [comment]
This software only expands features of Windows RDP service, not more, not less (see README).

For mirroring purposes, you may try TightVNC / UltraVNC.

**Comment by mackib** [comment]
Ok, i tought this maybe was possible to implement. Vnc clients are often very slow

**Comment by binarymaster** [comment]
You also may try RealVNC Enterprise or RAdmin, they are using mirror drivers to get better performance during remote assistance / administering. But these solutions aren't freeware.
