### ISSUE TITLE
rdp wrapper does no more work after patchday 02.02.2016 windows 10 to version 10586.71

### ISSUE THREAD

**Issue by arbyter1** [binarymaster/rdpwrap#87]
In RDP Wrapper Configuration it reports:
Wrapper state: Installe ver 1.5.0.0
Service start: Running ver. 10.0.10586.0
Listener state: Listening  [not supported]

Any hope to fix this?

**Comment by binarymaster** [comment]
Run update

**Comment by arbyter1** [comment]
thanks a lot:  would like to buy you some beers, where is your donate button ?

**Comment by binarymaster** [comment]
The ways of donating are described on our official site, in the "Donate" block on middle right of the each page.

**Comment by arbyter1** [comment]
and where ist your official site? Add a link to it, at least.
All i found was a russian site, which i dont understand.

mit freundlichen Grüssen

Robert Hofer
Hofercomputing GmbH
Haldenstrasse 19

3550 Langnau

034 402 70 55

rh@hofercomputing.ch




------ Originalnachricht ------
Von: "binarymaster" <notifications@github.com>
An: "binarymaster/rdpwrap" <rdpwrap@noreply.github.com>
Cc: "arbyter1" <rh@hofercomputing.ch>
Gesendet: 07.02.2016 09:36:35
Betreff: Re: [rdpwrap] rdp wrapper does no more work after patchday 
02.02.2016 windows 10 to version 10586.71 (#87)

**Comment by binarymaster** [comment]
@arbyter1 it's our site: http://stascorp.com/
Although, there is no english translated version of site, so you may use Google Translate.

Preferred donating way is WebMoney, here are our accounts:
WMZ: **Z358077191062**
WME: **E208225402366**
WMR: **R303537803958**

**Comment by grant-h** [comment]
Any way to do another release cut for convenience that way users don't have to run `update.bat` when they get 1.6?

**Comment by binarymaster** [comment]
@grant-h It's early to make a new release, since there are many plans for it. There is already created issue for it: https://github.com/stascorp/rdpwrap/issues/85
