### ISSUE TITLE
make it work with Teamviewer

### ISSUE THREAD

**Issue by BuzzD13** [binarymaster/rdpwrap#94]
Hi, is there a way to connect to the different usersessions via teamviewer?
I know, TV supports Terminal servers. But it seems, my Windows 10 with rdpwrap isn't regognized as such...

**Comment by binarymaster** [comment]
I have no experience using TeamViewer in different logon sessions, so I can only suggest that it needs to be installed as system service with persistent access.

**Comment by BuzzD13** [comment]
It's installed as a service but I'm guessing, the windows installation isn't recognized as a terminal server. Otherwise, I would be offered different teamviewer-IDs. As I understand it, there's one main "server-ID" and different user-IDs for the usersessions. Only, I don't see it.

**Comment by binarymaster** [comment]
I think you need to contact TeamViewer support about this, because RDP Wrapper can't make system be recognized as Terminal Server.
